development:
  adapter: mysql2
  encoding: utf8
  database: sampleapp_development
  username: root
  password:
  host: localhost
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: sampleapp_production
  username: root
  password:
  host: localhost
  port: 3306
